defmodule Calendrical.LunisolarTraditional.Test do
  @moduledoc """
  Regression tests for the lunisolar ordinal-vs-traditional month
  convention. Covers all three lunisolar calendars (Japanese, Chinese,
  Korean) which share the same `Calendrical.Lunisolar` core.

  The bug being protected against: prior to the fix, calling
  `<Calendar>.new(year, {m, :leap}, day)` with the documented
  traditional notation returned `{:error, :invalid_date}` because the
  Lunisolar validity check compared the user's traditional month number
  against the ordinal position returned by `leap_month/1`.

  """

  use ExUnit.Case, async: true

  # ── Calendrical.LunarJapanese ──────────────────────────────────────────────

  describe "Calendrical.LunarJapanese.new/3" do
    test "accepts traditional {M, :leap} for a known leap year" do
      # Y1210 = AD 1854 (Kaei 7). The Tenpō calendar of 1854 had an
      # intercalary 7th month (閏7月). In Calendrical's ordinal numbering
      # this is m8.
      assert {:ok, date} = Calendrical.LunarJapanese.new(1210, {7, :leap}, 1)
      assert date.month == 8
      assert {:ok, ~D[1854-08-24]} = Date.convert(date, Calendar.ISO)
    end

    test "rejects ordinal-pretending-to-be-traditional {M+1, :leap}" do
      assert {:error, :invalid_date} = Calendrical.LunarJapanese.new(1210, {8, :leap}, 1)
    end

    test "rejects {M, :leap} in a non-leap year" do
      assert {:error, :invalid_date} = Calendrical.LunarJapanese.new(1211, {7, :leap}, 1)
    end

    test "traditional integer month past the intercalary lands on the right Gregorian day" do
      # 嘉永7年11月27日 (Kaei 7-11-27) = 安政改元 (proclamation of Ansei).
      # Historical record: 1855-01-15 Gregorian. Because Y1210 has the
      # intercalary at traditional {7, :leap}, traditional M11 is ordinal m12.
      assert {:ok, date} = Calendrical.LunarJapanese.new(1210, 11, 27)
      assert date.month == 12
      assert {:ok, ~D[1855-01-15]} = Date.convert(date, Calendar.ISO)
    end

    test "traditional integer month before the intercalary equals the ordinal month" do
      assert {:ok, date} = Calendrical.LunarJapanese.new(1210, 7, 1)
      assert date.month == 7
      assert {:ok, ~D[1854-07-25]} = Date.convert(date, Calendar.ISO)
    end

    test "in a non-leap year, traditional integer month equals ordinal month" do
      assert {:ok, date} = Calendrical.LunarJapanese.new(1211, 11, 27)
      assert date.month == 11
    end
  end

  describe "Calendrical.LunarJapanese.new!/3" do
    test "returns a Date on valid input" do
      assert %Date{} = Calendrical.LunarJapanese.new!(1210, {7, :leap}, 1)
    end

    test "raises ArgumentError on invalid input" do
      assert_raise ArgumentError, fn ->
        Calendrical.LunarJapanese.new!(1211, {7, :leap}, 1)
      end
    end
  end

  describe "Calendrical.LunarJapanese leap-month accessors" do
    test "leap_month/1 returns the ordinal position (1..13)" do
      assert Calendrical.LunarJapanese.leap_month(1210) == 8
      assert Calendrical.LunarJapanese.leap_month(1379) == 3
      assert Calendrical.LunarJapanese.leap_month(1211) == nil
    end

    test "traditional_leap_month/1 returns the traditional number (1..12)" do
      assert Calendrical.LunarJapanese.traditional_leap_month(1210) == 7
      assert Calendrical.LunarJapanese.traditional_leap_month(1379) == 2
      assert Calendrical.LunarJapanese.traditional_leap_month(1211) == nil
    end

    test "traditional_leap_month accepts a Date" do
      date = Calendrical.LunarJapanese.new!(1210, 1, 1)
      assert Calendrical.LunarJapanese.traditional_leap_month(date) == 7
    end
  end

  describe "Date.new/4 — the ordinal path — is unaffected" do
    # `Date.new/4` calls the calendar's 3-arity `valid_date?/3` callback
    # (auto-generated by `Calendrical.Behaviour`, ordinal-month semantics),
    # not the 5-arity `valid_traditional_date?/5` inside `Calendrical.Lunisolar`.
    # The two functions answer different questions and the bug fix here
    # touches only the latter.

    test "ordinal m13 in a leap year is accepted" do
      assert {:ok, %Date{month: 13}} = Date.new(1210, 13, 1, Calendrical.LunarJapanese)
    end

    test "ordinal m13 in a non-leap year is rejected" do
      assert {:error, :invalid_date} = Date.new(1211, 13, 1, Calendrical.LunarJapanese)
    end

    test "ordinal m8 in Y1210 corresponds to the intercalary day-1 (1854-08-24)" do
      {:ok, date} = Date.new(1210, 8, 1, Calendrical.LunarJapanese)
      assert {:ok, ~D[1854-08-24]} = Date.convert(date, Calendar.ISO)
    end
  end

  # ── Calendrical.Chinese ────────────────────────────────────────────────────

  describe "Calendrical.Chinese.new/3" do
    test "accepts traditional {M, :leap} for Y4660 (= AD 2023)" do
      # Y4660 has the intercalary at traditional {2, :leap} = ordinal m3.
      assert {:ok, date} = Calendrical.Chinese.new(4660, {2, :leap}, 1)
      assert date.month == 3
      assert {:ok, ~D[2023-03-22]} = Date.convert(date, Calendar.ISO)
    end

    test "rejects ordinal {3, :leap}" do
      assert {:error, :invalid_date} = Calendrical.Chinese.new(4660, {3, :leap}, 1)
    end

    test "traditional integer month past intercalary maps to ordinal+1" do
      assert {:ok, date} = Calendrical.Chinese.new(4660, 3, 1)
      assert date.month == 4
      assert {:ok, ~D[2023-04-20]} = Date.convert(date, Calendar.ISO)
    end
  end

  describe "Calendrical.Chinese leap-month accessors" do
    test "leap_month/1 returns ordinal" do
      assert Calendrical.Chinese.leap_month(4660) == 3
      assert Calendrical.Chinese.leap_month(4661) == nil
    end

    test "traditional_leap_month/1 returns traditional" do
      assert Calendrical.Chinese.traditional_leap_month(4660) == 2
      assert Calendrical.Chinese.traditional_leap_month(4661) == nil
    end
  end

  # ── Calendrical.Korean ─────────────────────────────────────────────────────

  describe "Calendrical.Korean.new/3" do
    test "accepts traditional {M, :leap} for Y4356 (= AD 2023)" do
      assert {:ok, date} = Calendrical.Korean.new(4356, {2, :leap}, 1)
      assert date.month == 3
      assert {:ok, ~D[2023-03-22]} = Date.convert(date, Calendar.ISO)
    end

    test "rejects ordinal {3, :leap}" do
      assert {:error, :invalid_date} = Calendrical.Korean.new(4356, {3, :leap}, 1)
    end

    test "Buddha's birthday (lunar M4 D8) in a leap year lands on the correct Gregorian day" do
      # In Y4356, traditional M4 is ordinal m5 because the intercalary at {2, :leap}
      # shifts everything from M3 onwards by one ordinal position.
      assert {:ok, date} = Calendrical.Korean.new(4356, 4, 8)
      assert date.month == 5
    end
  end

  describe "Calendrical.Korean leap-month accessors" do
    test "leap_month/1 returns ordinal" do
      assert Calendrical.Korean.leap_month(4356) == 3
      assert Calendrical.Korean.leap_month(4357) == nil
    end

    test "traditional_leap_month/1 returns traditional" do
      assert Calendrical.Korean.traditional_leap_month(4356) == 2
      assert Calendrical.Korean.traditional_leap_month(4357) == nil
    end
  end
end
