defmodule Calendrical.DateTest do
  use ExUnit.Case, async: true

  doctest Calendrical.Date

  describe "Localize.DateTime.Formatter — non-Gregorian calendar integration" do
    test "Hebrew date renders correct ISO week — `:calendar.iso_week_number/1` was being called on the raw Hebrew y/m/d before the fix" do
      # 5784-09-12 Hebrew = 2024-05-20 Gregorian → ISO week 21
      # of 2024. The formatter now consults the calendar's
      # `iso_week_of_year/3` callback (returns `{:error,
      # :not_defined}` for Hebrew) and falls back to
      # converting to `Calendar.ISO` before computing the
      # week.
      {:ok, d} = Date.new(5784, 9, 12, Calendrical.Hebrew)
      assert {:ok, "21"} = Localize.DateTime.Formatter.format(d, "w", :"he-IL", %{})
      assert {:ok, "2024"} = Localize.DateTime.Formatter.format(d, "Y", :"he-IL", %{})
    end

    test "Gregorian-aligned calendars use their own iso_week_of_year callback" do
      # `Calendrical.Gregorian` implements
      # `iso_week_of_year/3` properly — the formatter should
      # use the callback, not the Erlang stdlib fallback.
      {:ok, d} = Date.new(2024, 7, 1, Calendrical.Japanese)
      # Calendrical.Japanese returns {:error, :not_defined} so
      # we fall back to ISO conversion. Result still correct.
      assert {:ok, "27"} = Localize.DateTime.Formatter.format(d, "w", :"ja-JP", %{})
    end

    test "Buddhist year renders correctly with ISO week" do
      {:ok, d} = Date.new(2569, 5, 16, Calendrical.Buddhist)
      assert {:ok, "20"} = Localize.DateTime.Formatter.format(d, "w", :"th-TH", %{})
    end
  end

  describe "parse/2 — Gregorian" do
    test "ISO 8601 always parses in every locale" do
      for locale <- [:en, :"en-GB", :de, :fr, :ja] do
        assert {:ok, ~D[2026-05-16]} = Calendrical.Date.parse("2026-05-16", locale: locale)
      end
    end

    test "en uses M/d ordering" do
      assert {:ok, ~D[2026-05-16]} = Calendrical.Date.parse("5/16/26", locale: :en)
    end

    test "en-GB uses d/M ordering" do
      assert {:ok, ~D[2026-05-16]} = Calendrical.Date.parse("16/05/2026", locale: :"en-GB")
    end

    test "de uses dd.MM ordering" do
      assert {:ok, ~D[2026-05-16]} = Calendrical.Date.parse("16.05.2026", locale: :de)
    end

    test "ja uses y/M/d ordering (Gregorian)" do
      assert {:ok, ~D[2026-05-16]} = Calendrical.Date.parse("2026/05/16", locale: :ja)
    end

    test "same input parses differently per locale" do
      assert {:ok, ~D[2026-03-04]} = Calendrical.Date.parse("3/4/26", locale: :en)
      assert {:ok, ~D[2026-04-03]} = Calendrical.Date.parse("3/4/26", locale: :"en-GB")
    end

    test "lenient separator equivalence — en accepts / - . interchangeably" do
      for sep <- ["/", "-", "."] do
        assert {:ok, ~D[2026-05-16]} =
                 Calendrical.Date.parse("5#{sep}16#{sep}26", locale: :en)
      end
    end

    test "lenient separator equivalence — de accepts . / - interchangeably" do
      for sep <- [".", "/", "-"] do
        assert {:ok, ~D[2026-05-16]} =
                 Calendrical.Date.parse("16#{sep}05#{sep}2026", locale: :de)
      end
    end

    test "non-breaking hyphen U+2011 is a lenient separator" do
      nbh = <<0x2011::utf8>>

      assert {:ok, ~D[2026-05-16]} =
               Calendrical.Date.parse("5" <> nbh <> "16" <> nbh <> "26", locale: :en)
    end

    test "out-of-calendar date rejected" do
      assert {:error, _} = Calendrical.Date.parse("2026-02-30", locale: :en)
    end

    test "garbage rejected with structured error" do
      assert {:error, %Calendrical.DateParseError{input: "garbage"}} =
               Calendrical.Date.parse("garbage", locale: :en)
    end

    test "two-digit year pivots forward for Gregorian only" do
      ref = ~D[2026-05-16]

      assert {:ok, ~D[2030-05-16]} =
               Calendrical.Date.parse("5/16/30", locale: :en, reference_date: ref)

      assert {:ok, ~D[1970-05-16]} =
               Calendrical.Date.parse("5/16/70", locale: :en, reference_date: ref)
    end
  end

  # CLDR `common/testData/datetime/datetime.json` —
  # generated by CLDR's `GenerateDateTimeTestData.java` tool.
  # Each entry pairs an ISO-8601 input with the expected
  # CLDR-formatted output for a (locale, calendar, length)
  # tuple. We use them in reverse: feed the expected
  # formatted string through our parser, assert it returns
  # the original date.
  @cldr_cases [
    %{locale: "en", calendar: :gregorian, input: ~D[2000-01-01], expected: "Jan 1, 2000"},
    %{locale: "en", calendar: :gregorian, input: ~D[2024-07-01], expected: "Jul 1, 2024"},
    %{locale: "en", calendar: :gregorian, input: ~D[2014-07-15], expected: "Jul 15, 2014"},
    %{
      locale: "ar-SA",
      calendar: :islamic_civil,
      input: ~D[2000-01-01],
      expected: "٢٤ رمضان ١٤٢٠ هـ"
    },
    %{
      locale: "ar-SA",
      calendar: :islamic_civil,
      input: ~D[2024-07-01],
      expected: "٢٤ ذو الحجة ١٤٤٥ هـ"
    },
    %{
      locale: "ar-SA",
      calendar: :islamic_civil,
      input: ~D[2014-07-15],
      expected: "١٧ رمضان ١٤٣٥ هـ"
    },
    %{locale: "th-TH", calendar: :buddhist, input: ~D[2000-01-01], expected: "1 ม.ค. 2543"},
    %{locale: "th-TH", calendar: :buddhist, input: ~D[2024-07-01], expected: "1 ก.ค. 2567"},
    %{locale: "th-TH", calendar: :buddhist, input: ~D[2014-07-15], expected: "15 ก.ค. 2557"},
    %{locale: "ja-JP", calendar: :japanese, input: ~D[2000-01-01], expected: "平成12年1月1日"},
    %{locale: "ja-JP", calendar: :japanese, input: ~D[2024-07-01], expected: "令和6年7月1日"},
    %{locale: "ja-JP", calendar: :japanese, input: ~D[2014-07-15], expected: "平成26年7月15日"}
  ]

  describe "parse_range/2 — pair form" do
    test "ISO endpoints round-trip" do
      assert {:ok, range} =
               Calendrical.Date.parse_range({"2026-05-05", "2026-05-10"}, locale: :en)

      assert range.first == ~D[2026-05-05]
      assert range.last == ~D[2026-05-10]
    end

    test "locale-formatted endpoints" do
      assert {:ok, range} =
               Calendrical.Date.parse_range(
                 {"May 5, 2026", "May 10, 2026"},
                 locale: :en
               )

      assert range.first == ~D[2026-05-05]
      assert range.last == ~D[2026-05-10]
    end

    test "de endpoints" do
      assert {:ok, range} =
               Calendrical.Date.parse_range(
                 {"5.5.2026", "10.5.2026"},
                 locale: :de
               )

      assert range.first == ~D[2026-05-05]
      assert range.last == ~D[2026-05-10]
    end

    test "inverted range rejected by default" do
      assert {:error, %Calendrical.DateRangeParseError{reason: :inverted}} =
               Calendrical.Date.parse_range({"2026-05-10", "2026-05-05"}, locale: :en)
    end

    test "inverted range accepted with allow_inverted: true" do
      assert {:ok, range} =
               Calendrical.Date.parse_range(
                 {"2026-05-10", "2026-05-05"},
                 locale: :en,
                 allow_inverted: true
               )

      assert range.first == ~D[2026-05-10]
      assert range.last == ~D[2026-05-05]
      assert range.step == -1
    end

    test "unparseable endpoint surfaces the underlying error" do
      assert {:error, %Calendrical.DateRangeParseError{reason: :from_parse_failed, cause: cause}} =
               Calendrical.Date.parse_range({"garbage", "2026-05-10"}, locale: :en)

      assert %Calendrical.DateParseError{input: "garbage"} = cause
    end
  end

  describe "parse_range/2 — single-string form" do
    test "ISO range with CLDR fallback separator (NNBSP + en-dash + NNBSP)" do
      assert {:ok, range} =
               Calendrical.Date.parse_range("2026-05-05 – 2026-05-10", locale: :en)

      assert range.first == ~D[2026-05-05]
      assert range.last == ~D[2026-05-10]
    end

    test "lenient separators — hyphen-minus" do
      assert {:ok, range} =
               Calendrical.Date.parse_range("May 5, 2026 - May 10, 2026", locale: :en)

      assert range.first == ~D[2026-05-05]
      assert range.last == ~D[2026-05-10]
    end

    test "lenient — 'to'" do
      assert {:ok, range} =
               Calendrical.Date.parse_range("May 5, 2026 to May 10, 2026", locale: :en)

      assert range.first == ~D[2026-05-05]
      assert range.last == ~D[2026-05-10]
    end

    test "missing separator yields :no_separator error" do
      assert {:error, %Calendrical.DateRangeParseError{reason: :no_separator}} =
               Calendrical.Date.parse_range("just one date", locale: :en)
    end
  end

  describe "parse_range/2 — non-ISO calendars" do
    test "Buddhist pair returns Date.Range with Buddhist endpoints" do
      assert {:ok, range} =
               Calendrical.Date.parse_range(
                 {"2026-05-05", "2026-05-10"},
                 locale: :en,
                 calendar: :buddhist
               )

      assert %Date.Range{} = range
      assert range.first == ~D[2569-05-05 Calendrical.Buddhist]
      assert range.last == ~D[2569-05-10 Calendrical.Buddhist]
      assert range.first.calendar == Calendrical.Buddhist
      assert range.last.calendar == Calendrical.Buddhist
    end

    test "Hebrew pair returns Date.Range with Hebrew endpoints" do
      assert {:ok, range} =
               Calendrical.Date.parse_range(
                 {"2026-05-05", "2026-05-10"},
                 locale: :en,
                 calendar: :hebrew
               )

      assert %Date.Range{} = range
      assert range.first == ~D[5786-09-18 Calendrical.Hebrew]
      assert range.last == ~D[5786-09-23 Calendrical.Hebrew]
      assert range.first.calendar == Calendrical.Hebrew
      assert range.last.calendar == Calendrical.Hebrew
    end

    test "Persian pair returns Date.Range with Persian endpoints" do
      assert {:ok, range} =
               Calendrical.Date.parse_range(
                 {"2026-05-05", "2026-05-10"},
                 locale: :en,
                 calendar: :persian
               )

      assert %Date.Range{} = range
      assert range.first.calendar == Calendrical.Persian
      assert range.last.calendar == Calendrical.Persian
    end

    test "Gregorian default returns Date.Range with Calendar.ISO endpoints" do
      assert {:ok, range} =
               Calendrical.Date.parse_range({"2026-05-05", "2026-05-10"}, locale: :en)

      assert %Date.Range{} = range
      assert range.first.calendar == Calendar.ISO
      assert range.last.calendar == Calendar.ISO
    end

    test "inverted Buddhist range with allow_inverted preserves calendar" do
      assert {:ok, range} =
               Calendrical.Date.parse_range(
                 {"2026-05-10", "2026-05-05"},
                 locale: :en,
                 calendar: :buddhist,
                 allow_inverted: true
               )

      assert %Date.Range{step: -1} = range
      assert range.first.calendar == Calendrical.Buddhist
      assert range.last.calendar == Calendrical.Buddhist
    end
  end

  describe "parse/2 — ISO 8601 formats beyond stdlib" do
    test "basic format YYYYMMDD" do
      assert {:ok, ~D[2026-05-23]} = Calendrical.Date.parse("20260523", locale: :en)
      assert {:ok, ~D[2000-02-29]} = Calendrical.Date.parse("20000229", locale: :en)
    end

    test "ordinal date YYYY-DDD" do
      assert {:ok, ~D[2026-05-23]} = Calendrical.Date.parse("2026-143", locale: :en)
      assert {:ok, ~D[2026-01-01]} = Calendrical.Date.parse("2026-001", locale: :en)
      assert {:ok, ~D[2024-12-31]} = Calendrical.Date.parse("2024-366", locale: :en)
    end

    test "ordinal date rejects out-of-range day-of-year" do
      assert {:error, _} = Calendrical.Date.parse("2026-366", locale: :en)
      assert {:error, _} = Calendrical.Date.parse("2026-000", locale: :en)
    end

    test "ISO week date YYYY-Www-D" do
      assert {:ok, ~D[2026-05-23]} = Calendrical.Date.parse("2026-W21-6", locale: :en)
      # 2020-W53 is a real 53-week year
      assert {:ok, ~D[2020-12-28]} = Calendrical.Date.parse("2020-W53-1", locale: :en)
    end

    test "ISO week date rejects week 53 in non-53-week year" do
      # 2025 is a 52-week ISO year (W53 would roll into 2026).
      assert {:error, _} = Calendrical.Date.parse("2025-W53-1", locale: :en)
    end
  end

  describe "parse/2 — M↔d swap synthesis" do
    test "English 'MMM d' pattern parses 'd MMM' input ('23 May' in :en)" do
      assert {:ok, ~D[2026-05-23]} = Calendrical.Date.parse("23 May", locale: :en)
    end

    test "French 'd MMM' pattern parses 'MMM d' input ('mai 23' in :fr)" do
      # Month name has to be in the locale's language ("mai", not
      # "May") — the swap reorders M and d but doesn't translate.
      assert {:ok, ~D[2026-05-23]} = Calendrical.Date.parse("mai 23", locale: :fr)
    end

    test "French native 'd MMM' still works" do
      assert {:ok, ~D[2026-05-23]} = Calendrical.Date.parse("23 mai", locale: :fr)
    end

    test "swap applies to year-bearing yMMMd patterns" do
      # English `:yMMMd` is "MMM d, y"; swapped is "d MMM, y".
      assert {:ok, ~D[2026-05-23]} = Calendrical.Date.parse("23 May, 2026", locale: :en)
    end

    test "swap applies to wide month names too (MMMM)" do
      # English `:MMMMd` is "MMMM d" (no comma); swap → "d MMMM".
      # Verify both orderings parse with the wide month name.
      assert {:ok, ~D[2026-05-23]} = Calendrical.Date.parse("May 23", locale: :en)
      assert {:ok, ~D[2026-05-23]} = Calendrical.Date.parse("23 May", locale: :en)
    end

    test "swap does NOT apply to numeric M (M/MM) — would be ambiguous with d" do
      # `5/16` in :en is M/d (May 16); the swap MUST NOT turn it
      # into d/M (5 May / "16 of month 5"). Numeric M (count < 3)
      # is excluded from the swap.
      assert {:ok, ~D[2026-05-16]} = Calendrical.Date.parse("5/16/26", locale: :en)
      # In :en-GB the same input is d/M (16 May). The native
      # ordering still wins; the swap doesn't apply here.
      assert {:ok, ~D[2026-04-03]} = Calendrical.Date.parse("3/4/26", locale: :"en-GB")
    end
  end

  describe "parse/2 — case-insensitive name matching (CLDR TR35 §6.5)" do
    test "French 'Mai' matches CLDR lowercase 'mai'" do
      assert {:ok, %Date{month: 5, day: 23}} =
               Calendrical.Date.parse("23 Mai 2026", locale: :fr)
    end

    test "French uppercase 'MAI' also matches" do
      assert {:ok, %Date{month: 5, day: 23}} =
               Calendrical.Date.parse("23 MAI 2026", locale: :fr)
    end

    test "English uppercase 'MAY' matches CLDR 'May'" do
      assert {:ok, %Date{month: 5, day: 23}} =
               Calendrical.Date.parse("MAY 23, 2026", locale: :en)
    end

    test "English lowercase weekday matches" do
      assert {:ok, ~D[2026-05-16]} =
               Calendrical.Date.parse("saturday, may 16, 2026", locale: :en)
    end
  end

  describe "parse/2 — :calendar option accepts a module" do
    test "Calendar.ISO is treated as :gregorian" do
      assert {:ok, ~D[2026-05-16]} =
               Calendrical.Date.parse("2026-05-16", locale: :en, calendar: Calendar.ISO)
    end

    test "Calendrical.Hebrew is equivalent to :hebrew" do
      assert {:ok, %Date{calendar: Calendrical.Hebrew} = d} =
               Calendrical.Date.parse("2026-05-16",
                 locale: :en,
                 calendar: Calendrical.Hebrew
               )

      {:ok, expected} =
        Calendrical.Date.parse("2026-05-16", locale: :en, calendar: :hebrew)

      assert d == expected
    end

    test "module form works for parse_range/2" do
      assert {:ok, range} =
               Calendrical.Date.parse_range(
                 {"2026-05-05", "2026-05-10"},
                 locale: :en,
                 calendar: Calendrical.Buddhist
               )

      assert range.first == ~D[2569-05-05 Calendrical.Buddhist]
      assert range.last == ~D[2569-05-10 Calendrical.Buddhist]
    end

    test "module form works for single-string parse_range/2" do
      assert {:ok, range} =
               Calendrical.Date.parse_range(
                 "2026-05-05 – 2026-05-10",
                 locale: :en,
                 calendar: Calendrical.Hebrew
               )

      assert range.first.calendar == Calendrical.Hebrew
      assert range.last.calendar == Calendrical.Hebrew
    end
  end

  describe "parse/2 — ROC (Minguo) era" do
    test "民國115年5月16日 (medium) → ROC 115-05-16 ≡ 2026-05-16" do
      assert {:ok, ~D[0115-05-16 Calendrical.Roc]} =
               Calendrical.Date.parse("民國115年5月16日",
                 locale: :"zh-Hant-TW",
                 calendar: :roc
               )
    end

    test "民國115/5/16 (short, with era marker) → ROC 115-05-16 ≡ 2026-05-16" do
      assert {:ok, ~D[0115-05-16 Calendrical.Roc]} =
               Calendrical.Date.parse("民國115/5/16",
                 locale: :"zh-Hant-TW",
                 calendar: :roc
               )
    end

    test "with `return_calendar: :iso` round-trips to Gregorian" do
      assert {:ok, ~D[2026-05-16]} =
               Calendrical.Date.parse("民國115年5月16日",
                 locale: :"zh-Hant-TW",
                 calendar: :roc,
                 return_calendar: :iso
               )
    end
  end

  describe "parse/2 — lenient spacing between adjacent fields" do
    test "ROC with optional space after era marker" do
      assert {:ok, ~D[0115-05-16 Calendrical.Roc]} =
               Calendrical.Date.parse("民國 115年5月16日",
                 locale: :"zh-Hant-TW",
                 calendar: :roc
               )
    end

    test "Japanese imperial with optional space after era marker" do
      assert {:ok, ~D[2000-01-01 Calendrical.Japanese]} =
               Calendrical.Date.parse("平成 12年1月1日",
                 locale: :"ja-JP",
                 calendar: :japanese
               )

      assert {:ok, ~D[2024-07-01 Calendrical.Japanese]} =
               Calendrical.Date.parse("令和 6年7月1日",
                 locale: :"ja-JP",
                 calendar: :japanese
               )
    end
  end

  describe "parse_range/2 — CLDR interval skeleton inheritance" do
    test "en — left side inherits year from right (MMMd M-differs)" do
      assert {:ok, range} =
               Calendrical.Date.parse_range("May 5 – May 10, 2026", locale: :en)

      assert range.first == ~D[2026-05-05]
      assert range.last == ~D[2026-05-10]
    end

    test "en — left side inherits month and year from right (yMMMd d-differs)" do
      assert {:ok, range} =
               Calendrical.Date.parse_range("May 5 – 10, 2026", locale: :en)

      assert range.first == ~D[2026-05-05]
      assert range.last == ~D[2026-05-10]
    end

    test "de — bare en-dash between days (yMd d-differs)" do
      assert {:ok, range} =
               Calendrical.Date.parse_range("5.–10.5.2026", locale: :de)

      assert range.first == ~D[2026-05-05]
      assert range.last == ~D[2026-05-10]
    end

    test "de — left day+month inherits year from right (yMd M-differs)" do
      assert {:ok, range} =
               Calendrical.Date.parse_range("5.5. – 10.5.2026", locale: :de)

      assert range.first == ~D[2026-05-05]
      assert range.last == ~D[2026-05-10]
    end
  end

  describe "parse/2 — CLDR round-trip" do
    for fixture <- @cldr_cases do
      @tag fixture: fixture

      test "#{fixture.locale}/#{fixture.calendar} parses #{inspect(fixture.expected)}",
           %{fixture: fixture} do
        locale = String.to_atom(fixture.locale)
        expected_date = fixture.input

        assert {:ok, parsed} =
                 Calendrical.Date.parse(fixture.expected,
                   locale: locale,
                   calendar: fixture.calendar
                 )

        # Result is ISO/Gregorian by default. Compare directly.
        assert Date.compare(parsed, expected_date) == :eq
      end
    end
  end
end
